name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build and Push Docker Image
      run: |
        docker build --build-arg GH_USER=${{ secrets.GH_USER }} \
                     --build-arg GH_TOKEN=${{ secrets.GH_TOKEN }} \
                     --build-arg GH_REPO=${{ secrets.GH_REPO }} \
                     -t ${{ secrets.DOCKER_USERNAME }}/GUARD:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/GUARD:latest
